# Generated by Django 6.0.4 on 2026-09-28 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Software",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=160, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Разработчик"
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("free", "Бесплатное"),
                            ("commercial", "Коммерческая лицензия"),
                            ("subscription", "Подписка"),
                            ("unknown", "Не указано"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Тип лицензии",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Где лежит лицензия, кто продлевает. Ключи здесь не храните.",
                        verbose_name="Примечание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Программа",
                "verbose_name_plural": "Программы",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="equipment",
            name="assigned_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_equipment",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Сотрудник (за кем закреплено)",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="hostname",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Имя компьютера в сети"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP-адрес"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="mac_address",
            field=models.CharField(blank=True, max_length=40, verbose_name="MAC-адрес"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="operating_system",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Операционная система"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Например: монитор — к ПК, виртуальная машина — к серверу.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="service.equipment",
                verbose_name="Подключено к / установлено на",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="purchase_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата покупки"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_use", "В работе"),
                    ("stock", "На складе"),
                    ("repair", "В ремонте"),
                    ("written_off", "Списано"),
                ],
                default="in_use",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="warranty_until",
            field=models.DateField(blank=True, null=True, verbose_name="Гарантия до"),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Телефон (внутренний)"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="position",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Должность"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Администратор"),
                    ("employee", "Сотрудник"),
                    ("operator", "Оператор"),
                    ("engineer", "Инженер"),
                    ("manager", "Руководитель"),
                ],
                default="employee",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
        migrations.AlterField(
            model_name="solution",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solutions",
                to="service.equipment",
                verbose_name="Оборудование",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                help_text="Можно не указывать, если вопрос не про конкретное устройство (доступы, почта, 1С).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="service.equipment",
                verbose_name="Оборудование",
            ),
        ),
        migrations.CreateModel(
            name="SoftwareInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(blank=True, max_length=60, verbose_name="Версия"),
                ),
                (
                    "license_until",
                    models.DateField(blank=True, null=True, verbose_name="Лицензия до"),
                ),
                (
                    "installed_at",
                    models.DateField(blank=True, null=True, verbose_name="Установлено"),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installations",
                        to="service.equipment",
                        verbose_name="Оборудование",
                    ),
                ),
                (
                    "software",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installations",
                        to="service.software",
                        verbose_name="Программа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Установленная программа",
                "verbose_name_plural": "Установленные программы",
                "ordering": ["software__name"],
                "unique_together": {("equipment", "software")},
            },
        ),
    ]
