# Generated by Django 6.0.4 on 2026-10-01 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_asset_registry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_scope',
            field=models.CharField(choices=[('all', 'Все новые заявки'), ('assigned', 'Назначенные мне')], default='assigned', max_length=20, verbose_name='События для звука'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_sound',
            field=models.BooleanField(default=False, verbose_name='Звук уведомлений'),
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'Создана'), ('assigned', 'Назначена')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_events_created', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_events_received', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='service.ticket')),
            ],
        ),
    ]
